In [ ]:

import numpy as np
a =np.linspace(1,2)
a


array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [ ]:
c = ([1,2,3],23,43)
print(len(c))
b = np.asarray(c)
print(b)

3
[list([1, 2, 3]) 23 43]


/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [ ]:
np.empty(2)

array([2.32988157e-316, 0.00000000e+000])

In [ ]:
a = np.ones_like((3,3))
a

array([1, 1])

In [ ]:
a = np.ones([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x = np.arange(6)
d = x.reshape(3,2)
d


array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a = np.zeros([1,3])
a

array([[0., 0., 0.]])

In [ ]:
c = np.zeros_like([2,4])
c

array([0, 0])

In [ ]:
a = np.array([1,4,5])
b = np.full((1,3),5)
b

array([[5, 5, 5]])

In [ ]:
x = np.arange(6)
print(x)


[0 1 2 3 4 5]


In [ ]:
print(np.eye(1,3))
print(np.identity(2))

[[1. 0. 0.]]
[[1. 0.]
 [0. 1.]]


In [ ]:
x = np.arange(9).reshape((3,3))
print(x)
np.diag(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

In [ ]:
print(np.diag(x,k=1))

[1 5]


In [ ]:
arr = np.arange(16).reshape(4,4)
arr = np.arange(16).reshape(2,2,4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [ ]:
print(arr.transpose(2,0,1))


[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]]


In [ ]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[[      -inf, 0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947, 1.94591015]],

       [[2.07944154, 2.19722458, 2.30258509, 2.39789527],
        [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]]])

In [ ]:
np.max(arr)

15

In [ ]:
np.min(arr)

0

In [ ]:
x = np.random.rand(8).reshape(2,4)
print(x)
y = np.array([[1,2,3,4],[8,9,5,6]])
print(y)

[[0.98618343 0.36353311 0.24650941 0.9719535 ]
 [0.48679382 0.52576656 0.36503266 0.34787031]]
[[1 2 3 4]
 [8 9 5 6]]


In [ ]:
np.maximum(x,y)

array([[1., 2., 3., 4.],
       [8., 9., 5., 6.]])

In [ ]:
np.minimum(x,y)

array([[0.98618343, 0.36353311, 0.24650941, 0.9719535 ],
       [0.48679382, 0.52576656, 0.36503266, 0.34787031]])

In [ ]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[9,10,11,12],[13,14,15,16]])

In [ ]:
np.concatenate([arr1,arr2],axis = 1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [ ]:
a=1;b=a
b

1

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b = a.ravel()
print(b)
b[0]=25
print(b)
print(a)

[1 2 3 4 5 6 7 8]
[25  2  3  4  5  6  7  8]
[[25  2  3  4]
 [ 5  6  7  8]]


In [ ]:
c = a.flatten()
print(c)

[25  2  3  4  5  6  7  8]


In [ ]:
import pandas as pd
import numpy as np
a = np.array([1,2,3])
#pandas.Series(data,index,dtype,copy)   --->index -->
b = pd.Series(a)
print(b)

0    1
1    2
2    3
dtype: int64


In [ ]:
c = {1:23, 2:21 }
d = pd.Series(c)
print(d)

1    23
2    21
dtype: int64


In [ ]:
#pandas.DataFrame(data,index,colums,dtype,copy)

In [ ]:
data = [['Alex',10],['Bob',14],['Rahul',18]]
df = pd.DataFrame(data)
print(df)

       0   1
0   Alex  10
1    Bob  14
2  Rahul  18


In [ ]:
df = pd.DataFrame(data, columns=['Name','Age'])
print(df)

    Name  Age
0   Alex   10
1    Bob   14
2  Rahul   18


In [ ]:
data = {0:0,1:1,2:4,3:9}
df = pd.DataFrame(data,index=[1])
print(df)

   0  1  2  3
1  0  1  4  9


In [ ]:
data = {'Name':['Tom','Rahul','Sam','Raghav'], 'Age':[14,15,16,18]}
df = pd.DataFrame(data, index=['S/o ram','S/o ravi','S/o siva','S/o balu'])
print(df)

            Name  Age
S/o ram      Tom   14
S/o ravi   Rahul   15
S/o siva     Sam   16
S/o balu  Raghav   18


In [ ]:
dt = {'one' : pd.Series([1,2,3], index=['a','b','c']),
        'two' : pd.Series([1,2,3,4], index=['a','b','c','d'])}
df = pd.DataFrame(dt)
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


In [ ]:
print(df.values)

[[ 1.  1.]
 [ 2.  2.]
 [ 3.  3.]
 [nan  4.]]


In [ ]:
print(df.dtypes)

one    float64
two      int64
dtype: object


In [ ]:
df.columns

Index(['one', 'two'], dtype='object')

In [ ]:
data = {'Name':['Tom','Rahul','Sam','Raghav'], 'Age':[14,15,16,18]}
df = pd.DataFrame(data, index=[0,1,2,3])
df

Name  Age
0     Tom   14
1   Rahul   15
2     Sam   16
3  Raghav   18

In [ ]:
df.columns

Index(['Name', 'Age'], dtype='object')

In [ ]:
data['Name']

['Tom', 'Rahul', 'Sam', 'Raghav']

In [ ]:
data['Age']

[14, 15, 16, 18]

In [ ]:
data

{'Age': [14, 15, 16, 18], 'Name': ['Tom', 'Rahul', 'Sam', 'Raghav']}

In [ ]:

df.loc[0]

Name    Tom
Age      14
Name: 0, dtype: object

In [ ]:
df.iloc[-1]

Name    Raghav
Age         18
Name: 3, dtype: object

In [ ]:
df.count()

Name    4
Age     4
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 256.0+ bytes


In [ ]:
df.describe()

Age
count   4.000000
mean   15.750000
std     1.707825
min    14.000000
25%    14.750000
50%    15.500000
75%    16.500000
max    18.000000

In [ ]:
a = pd.read_table("def.txt")
a


FileNotFoundError: ignored

In [ ]:
a.values

In [ ]:
a = pd.read_table("/content/ex1.csv")
a

In [ ]:
a = pd.read_table("/content/ex1.csv", sep=',')
a

In [ ]:
a = pd.read_csv("/content/ex1.csv")
a

In [ ]:
a.head()

In [ ]:
a.head(1)

In [ ]:
a.tail()

In [ ]:
a.tail(1)

In [ ]:
a = pd.read_html("/content/bank.html")
a

Day 3 starts now


In [ ]:
len(a)
t=a[0]
t.head()
t.isnull()

In [ ]:
t.isnull().sum()

In [ ]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)),columns=list('abcd'))
print(df1)

In [ ]:
df2 = pd.DataFrame(np.arange(21).reshape((3,7)),columns=list('abcdefg'))
print(df2)

In [ ]:
df2.loc[1,'b'] = np.nan

In [ ]:
df2

In [ ]:
df1 + df2

In [ ]:
df1.add(df2, fill_value=1)

In [ ]:
df = pd.DataFrame(np.random.randn(5,3),
                  index = ['a','h','c','i','e'],
                  columns = ['one','two','three'],
                  )

In [ ]:
df

In [ ]:
df2 = df.reindex(['a','b','c','d','e','f','g','h','i'])
df2

In [ ]:
df2.isnull()

In [ ]:
df2.fillna(0)

In [ ]:
df2

In [ ]:
#d=df2.fillna(0,inplace=True)

In [ ]:
df2

In [ ]:
df3 = df2.fillna(method= 'bfill')
df3

In [ ]:
df = pd.DataFrame([['ant','bee','cat'], ['dog', None, 'fly' ]])
df

In [ ]:
pd.isna(df)

In [ ]:
pd.isna(df[1])

In [ ]:
pd.isna(df[2])

In [ ]:
pd.isna(df.iloc[0])

In [ ]:
a = pd.read_csv("excel1.csv")

In [ ]:
a

In [ ]:
a.isnull().sum()

In [ ]:
#a.fillna(0)
a.dropna(axis=1)

In [ ]:
#a.fillna(0, inplace=True)

In [ ]:
a.dropna(axis=1, inplace=True)

In [ ]:
a

In [ ]:
df = pd.DataFrame({'A': ['foo','bar','foo','bar','foo','bar'],
                   'B': ['one','one','two','two','one','two'],
                   'c' : np.random.randn(6),'D': np.random.randn(6)})
df

In [ ]:
df.info()

In [ ]:
df.groupby(['A','B']).mean()

In [ ]:
dates = pd.date_range('30/12/2020',periods=10)
dates

In [ ]:
a = pd.Series(np.arange(10),index=dates)

In [ ]:
a

In [ ]:
a.to_csv("dates.csv")

In [ ]:
sample = pd.read_csv("/content/dates.csv")

In [ ]:
sample

In [ ]:
sample.to_html("dates.html")

In [ ]:
import requests

In [ ]:
url = "https://api.github.com/repos/pandas-dev/pandas/issues"

In [ ]:
r = requests.get(url)
r

In [ ]:
data = r.json()

In [ ]:
data[0]['title']

In [ ]:
issues = pd.DataFrame(data,columns=['number','title','labels','state'])
issues.head()

In [ ]:
XYZ_web = {"Day":[1,2,3,4,5,6],"Visitors":[1000,2000,3000,4000,5000,6000,],"Bouncerate":[20,21,22,24,25,26]}
df = pd.DataFrame(XYZ_web)

In [ ]:
df.set_index("Day",inplace=True)

In [ ]:
df

In [ ]:
df1 = pd.DataFrame({"Int_rate":[1,2,3,4],"IND_GDP":[25,40,85,65]},index= [2001,2002,2003,2004])

In [ ]:
df2 = pd.DataFrame({"Int_rate":[1,2,3,4],"IND_GDP":[25,40,85,65]},index= [2001,2002,2003,2004])


In [ ]:
merge = pd.merge(df1,df2)
merge

In [ ]:
Concat = pd.concat([df1,df2])
Concat

Visualization


In [ ]:
import matplotlib.pyplot as plt
a = [1,2,3,4,5]
plt.plot(a)
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("First graph")
plt.show()

In [ ]:
a = [1,2,3,4,5,28]
plt.plot(a,color='r')
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Second graph")
plt.show()

In [ ]:
from matplotlib import style
plt.style.available

In [ ]:
a = [1,2,3,4,5,28]
plt.plot(a,color='r')
plt.style.use(['ggplot','dark_background'])
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Second graph")
plt.legend(loc = 'best')
plt.show()

Bar graph

In [ ]:
plt.bar([1,2,3,4],[4,5,6,7],color = 'cyan')
plt.bar([2,4,6,8],[5,2,3,4],color = 'red')
plt.show()

In [ ]:
ages = [10,12,14,16,18,20,22,24,26,28,32,44,48,52,56,64,68,74,76,82,84,86,94,98]
bins = [10,20,30,40,50,60,70,80,90,100]
plt.hist(ages,bins,color='g',rwidth = 10.5)
plt.show()

In [ ]:
x = [1,2,3,4]
y = [4,5,6,7]
plt.scatter(x,y)
plt.show()

In [ ]:
plt.style.use('seaborn-whitegrid')
activities = ['sleeping','eating','working','reading','using phone']
s = [5,1,16,3,1]
cols = ['r','g','b','m','y']
plt.pie(s,labels=activities,colors=cols,startangle=60,shadow=True,explode=(0,0,0.1,0,0.5),autopct="%1.2f%%")
plt.title("daliy activities")
plt.show()

In [ ]:
from sklearn import preprocessing
data = {'price':[492,286,487,519,541,429]}
data

In [ ]:
price_frame = pd.DataFrame(data)
price_frame

In [ ]:
a = preprocessing.MinMaxScaler()
d = a.fit_transform(price_frame)
d

In [ ]:
c = pd.DataFrame(d)
c

0
1  23
2  21

In [ ]:
f = pd.DataFrame(data)
normalizer=preprocessing.scale(f)
normalizer

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(f)

In [ ]:
scaler.mean_

In [ ]:
scaler.transform(f)